using UnityEngine;
using UnityEngine.UI;

public class CollectLapTops : MonoBehaviour
{
    public int laptopValue = 1;  // םד בו בדדזב בז
    private int totalLaptops = 0;  // ב בדבם בבו בדדזב בדד

    public Text laptopCountText;  // ד בה   בו בדדזב

    private void OnTriggerEnter(Collider other)
    {
        if (other.CompareTag("Laptop"))  //  דד  ‗ה ב‗ה בם ד בד ו וז ו דדזב
        {
            CollectLaptop();  //  בב בד בו בדדזב
            Destroy(other.gameObject);  // דם בו בדדזב ד דו
        }
    }

    private void CollectLaptop()
    {
        totalLaptops += laptopValue;  // ם ב בדבם בבו בדדזב
        UpdateLaptopCountText();  // ם ה   בו בדדזב
    }

    private void UpdateLaptopCountText()
    {
        laptopCountText.text = "Laptops: " + totalLaptops.ToString();  // ם ה   בו בדדזב בל זו בדד
    }
}